

tasks:

  - name: djangoconfig
    init: |
      pip install django
    command: |
      python ./django-casorio/vercel_app/manage.py runserver

#  - name: heroku
#    init: |
#      curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

ports:
  - name: dev_View 
    port: 8000
    onOpen: open-browser