# example .gitpod.yml from https://github.com/gitpod-io/demo-multi-repo-frontend


tasks:
  - name: vercelconfig
    init: |
      echo aiaiai
    command: |
      export PATH=$PATH:/workspace/casorio/node_modules/.bin

  - name: djangoconfig
    init: |
      pip install django
    command: |
      python ./django-casorio/vercel_app/manage.py runserver

  - name: heroku
    init: |
      curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

ports:
  - name: dev_View 
    port: 8000
    onOpen: open-browser